baseURL = "https://renchiliu.com/"
title = "Renchi Liu"
theme = "PaperMod"
languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 10

[params]
  description = "Renchi's site about ideas and projects"
  author = "Renchi Liu"

  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true

[params.homeInfoParams]
  Title = "Hi, I'm Renchi 👋"
  Content = "iOS  • System Design •  AI"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/RENCHILIU"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/renchiliu"

[menu]

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

