baseURL = "https://renchiliu.com/"
languageCode = "en-us"
title = "Renchi's Blog"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "Welcome to My Blog 👋"
  Content = "I'm Renchi, a developer sharing thoughts, code, and ideas."

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

