baseURL = "https://renchiliu.com/"
title = "Renchi Liu"
theme = "PaperMod"
languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 10

[params]
  description = "Renchi's site about ideas and projects"
  author = "Renchi Liu"

  defaultTheme = "auto"  # dark, light, auto
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true

  # Regular Mode 
  homeInfoParams = {
    Title = "Hi, I'm Renchi 👋",
    Content = "iOS  • System Design •  AI"
  }

  socialIcons = [
    { name = "github", url = "https://github.com/RENCHILIU" },
    { name = "linkedin", url = "https://linkedin.com/in/renchiliu" }
  ]

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
